#
# Данный модуль содержит некоторые коды ошибок Api <https://vk.com/dev/errors>
#

UNKNOWN_ERROR_OCCURRED = 1
UNKNOWN_METHOD_PASSED = 3
INCORRECT_SIGNATURE = 4
USER_AUTHORIZATION_FAILED = 5
TOO_MANY_REQUESTS_PER_SECOND = 6
INVALID_REQUEST = 8
FLOOD_CONTROL = 9
INTERNAL_SERVER_ERROR = 10
CAPTCHA_NEEDED = 14
ACCESS_DENIED = 15
HTTP_AUTHORIZATION_FAILED = 16
VALIDATION_REQUIRED = 17
THIS_METHOD_WAS_DISABLED = 23
CONFIRMATION_REQUIRED = 24
INVALID_APPLICATION_API_ID = 101
INVALID_USER_ID = 113
INVALID_TIMESTAMP = 150
ACCESS_TO_ALBUM_DENIED = 200
ACCESS_TO_AUDIO_DENIED = 201
ACCESS_TO_GROUP_DENIED = 203
THIS_ALBUM_IS_FULL = 300
SOME_ADS_ERROR_OCCURED = 603
